# Generated by Django 3.0.2 on 2020-01-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, upload_to='quiz/images/', verbose_name='image'),
        ),
    ]
