# Generated by Django 3.0.2 on 2020-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191115_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_subscribed_to_the_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
