# Generated by Django 3.0.2 on 2020-01-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-post_date',)},
        ),
    ]
